version: '3.3'
services:
  web:
    container_name: tubes-1
    user: "1000:1000"
    image: tubes-1:latest
    ports:
      - 8000:80
    depends_on:
      - db
    volumes: 
      - ./app:/var/www/html/
    networks:
      - wbd-network
    expose:
      - '80'
  db:
    container_name: wbd-db
    user: "1000:1000"
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'wbd-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - '9096:3306'
    expose:
      - '3306'
    networks:
      - wbd-network
  data-seeding:
    container_name: python-seeding
    image: python:3.7
    volumes:
      - ./db-init/seeding/:/app
    working_dir: /app
    command: ["sh", "all.sh"]
    depends_on:
      - web
      - db
    networks:
      - wbd-network
networks:
  wbd-network: