version: '3.3'
services:
  web:
    container_name: tubes-1
    user: "1000:1000"
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    depends_on:
      - db
    volumes: 
      - ./app:/var/www/html/
    expose:
      - '80'
    links:
      - db
  db:
    container_name: wbd-db
    user: "1000:1000"
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/mysql2:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '9096:3306'
    expose:
      - '3306'